### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by TylerS1066** [pmdevita/CreeperHeal2#20]
```
[19:07:36] [Server thread/INFO]: [CreeperHeal2] Enabling CreeperHeal2 v2.0.0
[19:07:36] [Server thread/ERROR]: Error occurred while enabling CreeperHeal2 v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/FactionsPlugin
	at net.pdevita.creeperheal2.compatibility.Factions.setPluginReference(Factions.kt:23) ~[?:?]
	at net.pdevita.creeperheal2.compatibility.FactionsProxy.setPluginReference(Factions.kt) ~[?:?]
	at net.pdevita.creeperheal2.compatibility.CompatibilityManager.loadCompatibilityPlugins(CompatibilityManager.kt:20) ~[?:?]
	at net.pdevita.creeperheal2.CreeperHeal2.onEnable(CreeperHeal2.kt:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.FactionsPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-"6f03c0a5"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
[19:07:36] [Server thread/INFO]: [CreeperHeal2] Disabling CreeperHeal2 v2.0.0
```

**Comment by pmdevita** [comment]
Huh that's weird, do you have Factions running on your server?

**Comment by pmdevita** [comment]
Yep, I know exactly why. It just checks that the server has a plugin named "Factions" loaded and then attempts to load compatibility for the FactionsUUID one. 

https://github.com/pmdevita/CreeperHeal2/blob/6d9aaba7cdc97b4180fd1fa451d5f54653e42396/src/main/kotlin/net/pdevita/creeperheal2/compatibility/CompatibilityManager.kt#L17

Getting the full path of a plugin's class as a string would make for a much better comparison, I'll look into swapping to that.

**Comment by TylerS1066** [comment]
Not sure if you intended for this to close, I made the mistake of mentioning it as fixed in my PR.

**Comment by pmdevita** [comment]
Ah I think that just happened automatically from the pull request, opened again.

**Comment by pmdevita** [comment]
Will be properly fixed in the next release.
